version: 2.1

jobs:
  analyze:
    docker:
      - image: 'cimg/openjdk:21.0.2'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=dawncoll_sample-spring-boot-app -Dsonar.organization=dawncoll -Dsonar.login=${{ SONARCLOUD_TOKEN }}

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:21.0.2'

orbs:
  maven: circleci/maven@1.4.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk
      - analyze:
          context: SonarCloud
